### ISSUE TITLE
Polygon daatasource

### ISSUE THREAD

**Issue by rrupesh** [javabudd/jtrader#8]
Hi @javabudd! first thing, amazing work! 👍 

I was wondering if you have plans to use a different data provider, like polygon.io?

One of the main reason to ask this question is to see if real-time analysis can be perform in your app. i.e., consuming websocket data and spitting out the info!

**Comment by javabudd** [comment]
I am in the process of splitting the historical data into an AWS DynamoDB table for further processing. As far as intraday data is concerned, this can absolutely be updated to support polygon.io as another provider. I need to do some cleanup on the configuration part but ideally this will just be a `providers` key in the jtrader.yml config.

**Comment by javabudd** [comment]
https://github.com/javabudd/jtrader/issues/9
